### ISSUE TITLE
[PE-D] Picture command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-4/tp#106]
In the spirit of being a CLI app, perhaps you could enable the end user to also specify file paths instead of using the file browser.

Example:

picture 1 ~/desktop/pic.png

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: cyyeu/ped#3

**Comment by david-eom** [comment]
Upon discussion with the team, the issue brought up is a feature request rather than bug report, thus closing the issue during triaging.
