### ISSUE TITLE
[PE-D] Remarks cannot be longer than window width

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-4/tp#107]
Cannot see much of the remarks as anything longer than my window width, the remark is cut off and there is no function for me to see the full remarks. As a user, since i have to keep track of so many friends, i certainly cannot remember what i wrote.

[Screen Recording 2021-10-29 at 16.51.46.mov](https://raw.githubusercontent.com/sheehui/ped/main/files/879ba399-1351-4238-8ace-71ea68a7a2ac.mov)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sheehui/ped#4

**Comment by david-eom** [comment]
This issue should be fixed as long as #149 is merged.
