### ISSUE TITLE
[PE-D] Help command only works if all is in lowercase

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-4/tp#111]
Not sure if it matters, but perhaps can change it to allow for non-exact commands like "HELP" or "Help"

![image.png](https://raw.githubusercontent.com/Imerbear/ped/main/files/9d18329b-4f62-49d4-bec1-fd3c1efbe4a5.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Imerbear/ped#5

**Comment by david-eom** [comment]
Upon discussion with the team, the issue brought up is a feature request rather than bug report, thus closing during traiging.
