### ISSUE TITLE
[PE-D] Date field would be missing on person card if label for date is too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-4/tp#114]
Date field would be missing on person card if label for date is too long
Command used: 
add n/001     p/98765432 t/friends t/owesMoney fb/           john.doe    ig/john.doe tele/johndoe tiktok/johndoe twitter/johndoe date/birthday:2000-01-01 date/birthday:2000-01-01 date/birthday:2000-01-01 date/dgadslkghasdjkhgasdjlkhgsajkdlgkjlhaskljdhgkhkajsdhgklhksagljkflhasdkgjasdhglsahdjkghjkahsdjkghkhajsdhgjhkjasdkjgkjasdkghkahsdg1234567890dhkglhaksdhghkasdg:2021-10-31
![image.png](https://raw.githubusercontent.com/Imerbear/ped/main/files/856af74c-dacb-4be0-ac24-7c505dadfe9c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Imerbear/ped#6

**Comment by david-eom** [comment]
The implementation should be quite similar with #149!
